### ISSUE TITLE
Rawgit CDN problem

### ISSUE THREAD

**Issue by IgnaciodeNuevo** [opentok/accelerator-textchat-js#28]
Hi:

We have a problem with Rawgit, we've been using https://cdn.rawgit.com/opentok/opentok.js-text-chat/master/dist/opentok-text-chat.js for two months and now it has been removed from the CDN, since this is critikal for our company we would love if you could help us in some way.

We thought accelerator-textchat-js was the replacement but after importing it to our website it didn't worked.

Thanks in advance,
Ignacio

**Comment by maikthomas** [comment]
Hi Ignacio, 

Accelerator-textchat-js is the current supported textchat version.
What issues are you having integrating the new textchat? Perhaps we can help to resolve them?

Thanks,
Mike

**Comment by IgnaciodeNuevo** [comment]
Hello @maikthomas 

We are trying to make the text chat work with the new source library, but it looks like that it needs external js scripts like moment.js, and underscore. From the source code, I suppose that you build the library with some module bundler like webpack.

We are not using any module bundlers at this moment, is there any way for downloading the script with all of these libraries included to make it work out of the box? We tried to import this libraries before the actual script but unfortunately it didn't work.

Kind regards.

**Comment by maikthomas** [comment]
@IgnaciodeNuevo In general we find webpack to be useful for this, however we have an example done without a bundler and I'll describe what we do below. I hope this will help in your case.
Kind regards,
Mike

## Using accelerator-textchat-js and dependencies without a module bundler
The dependencies are listed in the  [`package.json` file](https://github.com/opentok/accelerator-textchat-js/blob/master/package.json)
```
  "dependencies": {
    "jquery": "^3.1.0",
    "kuende-livestamp": "^1.1.2",
    "moment": "^2.14.1",
    "opentok-solutions-logging": "^1.0.6",
    "underscore": "^1.8.3"
  }
```
These all need to be included in your html before `opentok-text-chat.js`.
You can install all of these using:
`npm install opentok-text-chat`
which will give an output like this
```
└─┬ opentok-text-chat@1.0.29 
  ├── jquery@3.2.1 
  ├── kuende-livestamp@1.1.2 
  ├── moment@2.18.1 
  ├─┬ opentok-solutions-logging@1.0.10 
  │ └─┬ axios@0.15.3 
  │   └─┬ follow-redirects@1.0.0 
  │     └─┬ debug@2.6.3 
  │       └── ms@0.7.2 
  └── underscore@1.8.3 
``` 
You will want to copy the specific files over to your js assets folder to be used.
There is an example of this being done in the build script for the  [vanilla-js-sample-app](https://github.com/opentok/accelerator-sample-apps-js/tree/master/vanilla-js-sample-app). In the [`index.html`](https://github.com/opentok/accelerator-sample-apps-js/blob/master/vanilla-js-sample-app/public/index.html) we see the following:
```
  <script src="https://static.opentok.com/v2/js/opentok.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/livestamp/1.1.2/livestamp.min.js"></script>
    <script src="js/components/opentok-solutions-logging.js"></script>
    <script src="js/components/opentok-text-chat.js"></script>
```
So some of the requirements are being sourced from cloudflare. The `opentok-solutions-logging.js` `opentok-text-chat.js` files however have been placed in the components folder. This is done in the build scripts in the sample apps [`package.json`](https://github.com/opentok/accelerator-sample-apps-js/blob/master/vanilla-js-sample-app/package.json)
The files are installed via npm and are located at `node_modules/opentok-solutions-logging/dist/opentok-solutions-logging.js` and `node_modules/opentok-text-chat/dist/opentok-text-chat.js`
The build script used for this application simply copies these files into a js/components folder which is then served to the front-end.
The cp commands used by the build script:
```
    "cp-text-chat": "cp node_modules/opentok-text-chat/dist/opentok-text-chat.js public/js/components/",
    "cp-logging": "cp node_modules/opentok-solutions-logging/dist/opentok-solutions-logging.js public/js/components/",
```

**Comment by jesusbotella** [comment]
Thank you for your help @maikthomas! We made it work by applying your solution in our code. We are integrating it into Wordpress and we are not using module bundlers in this project, but it would have been easier with them.

We have one more issue with the chat stylesheet. The chat is working as expected but the injected <head> styles do not match any of the CSS classes that the DOM elements have, so it has no styles.

**Comment by maikthomas** [comment]
@IgnaciodeNuevo @jesusbotella 
Glad it worked!

Which stylesheet are you using? Is it the `theme.css` from the dist file of text-chat downloaded from npm?
Have you tried the [`opentok-solutions-css`](https://github.com/opentok/solutions-css)?
You can try it by just inserting the link.
`<link rel="stylesheet" href="https://assets.tokbox.com/solutions/css/style.css">
`
Let me know how it goes,
Mike

**Comment by IgnaciodeNuevo** [comment]
Thank you so much. Now it's ok and working

**Comment by maikthomas** [comment]
@IgnaciodeNuevo Great 👍
