### ISSUE TITLE
Chat input cleared on message received

### ISSUE THREAD

**Issue by VincentCtr** [opentok/accelerator-textchat-js#32]
#### Expected behavior

When a user receive a message and is currently writing a message:
- The text input should not be cleared

#### Actual behavior

When a user receive a message and is currently writing a message:
- Text input is cleared

#### Steps to reproduce

- Write a message and receive another one (bug does not happen if the message received is a append to the previous one)

After a quick review everything happens here:

  var _renderChatMessage = function (messageSenderId, messageSenderAlias, message, sentOn) {

    var sentByClass = _sender.id === messageSenderId ?
      'ots-message-item ots-message-sent' :
      'ots-message-item';

    var view = _getBubbleHtml({
      username: messageSenderAlias,
      message: message,
      messageClass: sentByClass,
      time: sentOn
    });

    var chatholder = $(_newMessages);
    chatholder.append(view);
    _cleanComposer();
    chatholder[0].scrollTop = chatholder[0].scrollHeight;

  };

We should add a test before  "_cleanComposer".

Can you do something for this ?

Thanks

**Comment by maikthomas** [comment]
Hi @VincentCtr,
Thanks for letting us know about this Issue. I've put in a PR and hopefully this will be published asap.

If you have any more issues let us know, or feel free to submit a PR!
You can see the contribution guidelines here: https://github.com/opentok/accelerator-textchat-js#contribute

Cheers,
Mike

**Comment by maikthomas** [comment]
@VincentCtr, this has now been fixed and uploaded to npm. The fix is in [release v1.0.30](https://github.com/opentok/accelerator-textchat-js/releases/tag/v1.0.30) on github and npm.
Thanks again,
Mike
