### ISSUE TITLE
Issue with `alwaysOpen` being limiting.

### ISSUE THREAD

**Issue by agionfriddo** [opentok/accelerator-textchat-js#37]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [X] I have searched [existing issues](https://github.com/opentok/accelerator-textchat-js/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 1.0.30
- iOS/Android/Browser version(s): Chrome 80.0.3987.163
- Devices/Simulators/Machine affected: N/A
- Reproducible in the demo project? (Yes/No): N/A
- Related issues: N/A

#### Expected behavior

> N/A

#### Actual behavior

> N/A

#### Steps to reproduce

> N/A

#### Crash log? Screenshots? Videos? Sample project?

>N/A

## Question or Feature Request

In the accelerator pack there are currently two options:

1. `alwaysOpen: true` where the chat is automatically started and displayed, but the button for toggling the chat is hidden. 
2. `alwaysOpen: false` where the chat is NOT started and displayed until the chat button is clicked. The display can be toggled with the chat button

Is there a way to make it so that when the application begins, the chat is automatically started and the display is able to be toggled on and off?

My exact use case is that if two users are in the video call, I want them to be able to send and receive chats from the beginning of the call without needing either of them to click the button. However, I don't want the chat to show all of the time. I was going to show a notification ping when a chat is received. However, I cannot do that until the chat is manually turned on by the user.

**Comment by MichaelJolley** [comment]
Fantastic suggestion @agionfriddo!  I'm going to work on this.

**Comment by MichaelJolley** [comment]
@agionfriddo, I've got a PR opened for this.

Notes from that PR are:

> Currently, when providing `alwaysOpen: true` the controls are always hidden. The `appendControl` option already exists and is used when `alwaysOpen: false`. This PR changes that behavior to allow `appendControl` to force adding the controls even when `alwaysOpen: true`.

So to get what you're looking for send the following config options:

```JS
  alwaysOpen: true,
  appendControl: true,
```
