### ISSUE TITLE
XSS Vulnerability In Chat

### ISSUE THREAD

**Issue by hamzanasir** [opentok/accelerator-textchat-js#46]
## New issue checklist

- [ ] I have read all of the [`README`](../README.md) 
- [ ] I have searched [existing issues](https://github.com/opentok/accelerator-textchat-js/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS/Android/Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

#### Expected behavior

> Do not accept script tags through chat.

#### Actual behavior

> While being in the chat window it is possible to inject <script> tags with various payloads and they will execute in all participants windows. An example payload <script>alert(XSS)</script> will render a popup for all participants. 

#### Steps to reproduce

Send a script tag through chat

> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by agonza1** [comment]
Hi @ggoldens @marinaserranomontes , first of all thanks for taking care of this fix(https://github.com/opentok/accelerator-textchat-js/pull/42) so quickly. 
We have a large application in production that depends on this... Do you have an estimate of when you will have your next  accelerator-textchat-js release?

**Comment by MichaelJolley** [comment]
Hi @agonza1, I'm working to get a release out today.

**Comment by MichaelJolley** [comment]
v1.0.31 is now in the wild with this fix.  Thanks!
